name = "parse_args"
description = "An Ada 2012 package to parse command line arguments and options"
version = "0.1.0"
website = "https://github.com/jhumphry/parse_args"
licenses = "ISC"
tags = ["cli", "command-line"]

authors = ["James Humphry"]
maintainers = ["James Humphry <example@example.com>"]
maintainers-logins = ["jhumphry"]
