name = "parse_args_examples"
description = "Examples of parse_args usage"
version = "0.1.0"
website = "https://github.com/jhumphry/parse_args"
licenses = "ISC"
tags = ["cli", "command-line"]

authors = ["James Humphry"]
maintainers = ["James Humphry <example@example.com>"]
maintainers-logins = ["jhumphry"]

executables = ["trivial_example", "simple_example", "generic_example"]

[configuration]
disabled = true

[[depends-on]]
parse_args = "*"

[[pins]]
parse_args = { path = "../" }